:general:
  date_template: '%Y-%m-%d'
  :strict: false
 
:templates:
  - { location: templates/default_id_report.md, output: ids.md }
  - { location: templates/default.md, output: default.md }
  - { location: templates/default_html.html, pdf: true, output: default.html }

:task_systems:
  -
    :name: jira
    :query_string: "https://api.github.com/repos/Praqma/Praqmatic-Automated-Changelog/issues/#{task_id}"
    :usr: jankrag@gmail.com  
    :pw: 
    :regex:
    - { pattern: '/#(\d+)/', label: github }
    :debug: false
  
:vcs:
  :type: git
  :usr:
  :pwd:
  :repo_location: '.'
  :release_regex: 'tags'
