FROM ruby:2.4.1-alpine

RUN sed -i -e 's/dl-cdn/dl-4/' /etc/apk/repositories
RUN apk add --no-cache \
	make \
	cmake 

#This istalls a patched version of wkhtmltopdf that allows it to run headless without configuration
RUN mkdir -p /var/lib/wkhtml
WORKDIR /var/lib/wkhtml
RUN wget http://download.gna.org/wkhtmltopdf/0.12/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz && \
		tar -xvf wkhtmltox-0.12.3_linux-generic-amd64.tar.xz && \
		rm wkhtmltox-0.12.3_linux-generic-amd64.tar.xz && \ 
		ln -sf /var/lib/wkhtml/wkhtmltox/bin/wkhtmltopdf /usr/bin/wkhtmltopdf

ADD Gemfile .
RUN bundle install 

